openapi: 3.0.0
info:
  title: SSE and Request Forwarding API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Successfully running service
  /register/{component-name}:
    get:
      summary: Register a client for SSE
      parameters:
        - name: component-name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully registered for SSE

  /request/{component-name}/{path}:
    parameters:
      - name: component-name
        in: path
        required: true
        schema:
          type: string
      - name: path
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Forward a GET request to the client
      responses:
        "200":
          description: Request forwarded successfully
    post:
      summary: Forward a POST request to the client
      responses:
        "200":
          description: Request forwarded successfully
    put:
      summary: Forward a PUT request to the client
      responses:
        "200":
          description: Request forwarded successfully
    delete:
      summary: Forward a DELETE request to the client
      responses:
        "200":
          description: Request forwarded successfully

  /response/{component-name}:
    post:
      summary: Handle response from client
      parameters:
        - name: component-name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Response handled successfully

  /handle/{component-name}:
    post:
      summary: Handle request from client
      parameters:
        - name: component-name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Request handled successfully
